// <auto-generated />
namespace PredictionOfDelays.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddValidationOfEvents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddValidationOfEvents));
        
        string IMigrationMetadata.Id
        {
            get { return "201803251812467_AddValidationOfEvents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
