// <auto-generated />
namespace PredictionOfDelays.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class GroupInvites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GroupInvites));
        
        string IMigrationMetadata.Id
        {
            get { return "201804261208522_GroupInvites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
