// <auto-generated />
namespace PredictionOfDelays.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Localizationv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Localizationv2));
        
        string IMigrationMetadata.Id
        {
            get { return "201804051433298_Localizationv2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
